### PR TITLE
Adds where to download pdftotext

### PR DESCRIPTION
**Pull request by stanparker**
Took me a while to figure out I needed this and where to get it.

### CODE REVIEW

**Comment by stanparker** [comment]
Haha... had I just looked at the source I would have seen it. never mind.

**Comment by dannguyen** [comment]
Thanks for the suggestion...I know it's buried in the comments, but did the link here not work for you:

https://github.com/compjour/search-script-scrape/blob/master/scripts/50.py#L15
http://www.foolabs.com/xpdf/download.html

I actually think I might have used Homebrew on my own system...

http://brewformulas.org/Xpdf

**Comment by stanparker** [comment]
I think we commented at the same time. I literally just saw that link in the comments right before you posted that.

**Comment by stanparker** [comment]
Thanks for chiming in to help. As a novice, I really appreciate it. These are some fun scripts to play around with.

**Pull request closed without merging**
